import { GoogleGenAI } from "@google/genai";
import { Resume, ChatMessage } from "../types";

const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

export const generateCoverLetter = async (
  jobRole: string,
  company: string,
  userSkills: string,
  jobDescription?: string
): Promise<string> => {
  if (!apiKey) return "Error: API Key is missing.";

  try {
    const prompt = `Write a passionate and professional cover letter for the role of ${jobRole} at ${company}. 
    My key skills are: ${userSkills}. 
    ${jobDescription ? `Here is the job description for context: ${jobDescription}` : ''}
    Keep it concise (under 300 words), engaging, and persuasive. Format it ready to copy-paste.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    return response.text || "Failed to generate cover letter.";
  } catch (error) {
    console.error("Gemini API Error:", error);
    return "An error occurred while generating the cover letter. Please try again.";
  }
};

export const generateOfferStrategy = async (
  jobRole: string,
  company: string,
  salary: string
): Promise<string> => {
  if (!apiKey) return "Error: API Key is missing.";

  try {
    const prompt = `I have received a job offer for ${jobRole} at ${company} with a salary/package of ${salary}. 
    Provide a negotiation strategy, 3 key questions I should ask before accepting, and a brief checklist for success in the first 90 days. 
    Format the output with clear Markdown headings.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    return response.text || "Failed to generate offer strategy.";
  } catch (error) {
    console.error("Gemini API Error:", error);
    return "An error occurred while analyzing the offer.";
  }
};

export const enhanceResumeText = async (
  text: string,
  type: 'summary' | 'experience' | 'project'
): Promise<string> => {
  if (!apiKey) return "Error: API Key is missing.";
  
  if (!text) return "";

  try {
    let prompt = "";
    
    if (type === 'summary') {
      prompt = `Rewrite the following professional summary to be more impactful, concise, and professional: "${text}"`;
    } else if (type === 'project') {
       prompt = `Rewrite the following project description to highlight technical challenges, specific technologies used, and outcomes. Keep it concise: "${text}"`;
    } else {
      prompt = `Rewrite the following job experience description to use strong action verbs, quantify results where possible, and improve clarity. Keep it in bullet points if applicable: "${text}"`;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    return response.text || text;
  } catch (error) {
    console.error("Gemini API Error:", error);
    return text; // Return original text if error
  }
};

export const generateAvatar = async (
  imageBase64: string,
  stylePrompt: string
): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing.");

  try {
    // Clean base64 string
    const base64Data = imageBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');
    
    const prompt = `Transform this portrait into a high-quality professional corporate headshot.
    Style requirements: ${stylePrompt}. 
    Maintain the person's identity and facial features, but improve the lighting to be studio quality, ensure neutral professional background, and attire to be strictly professional business wear. 
    Output ONLY the image.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: 'image/jpeg',
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini Avatar Error:", error);
    throw error;
  }
};

export const parseResumeFromImage = async (imageBase64: string): Promise<Partial<Resume>> => {
  if (!apiKey) throw new Error("API Key is missing.");

  try {
    const base64Data = imageBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');
    
    const prompt = `Analyze this resume image. Extract structured data into JSON matching the following schema. 
    Improve wording to be action-oriented where possible.
    
    Schema:
    {
      "fullName": "string",
      "email": "string",
      "phone": "string",
      "linkedin": "string",
      "location": "string",
      "summary": "string",
      "skills": "string (comma separated)",
      "experience": [ { "role": "string", "company": "string", "startDate": "string", "endDate": "string", "description": "string" } ],
      "projects": [ { "name": "string", "technologies": "string", "link": "string", "description": "string" } ],
      "education": [ { "degree": "string", "school": "string", "year": "string" } ]
    }
    
    Return ONLY the raw JSON string, no markdown formatting.`;

    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: {
        parts: [
          {
             inlineData: {
               data: base64Data,
               mimeType: 'image/jpeg', // Assuming jpeg/png for simplicity, generally robust
             }
          },
          { text: prompt }
        ]
      }
    });

    const text = response.text;
    if (!text) throw new Error("No response from model");

    // Clean markdown if present
    const cleanText = text.replace(/```json/g, '').replace(/```/g, '').trim();
    return JSON.parse(cleanText);

  } catch (error) {
    console.error("Gemini Parse Resume Error:", error);
    throw error;
  }
};

export const chatWithChatur = async (
  history: ChatMessage[], 
  userMessage: string,
  contextData: any
): Promise<string> => {
  if (!apiKey) return "I'm having trouble connecting to my brain right now. Please check your API key.";

  try {
    const systemInstruction = `You are Chatur, a friendly, empathetic, and intelligent career coach. 
    Your goal is to help the user get a job.
    
    Current User Context:
    - Application Stats: ${JSON.stringify(contextData.stats)}
    - Recent Applications: ${JSON.stringify(contextData.recentJobs)}
    
    Guidance Logic:
    - If their interview rate (interviews/applied) is < 10%, suggest resume tweaks or skill building.
    - If they have a new 'Interview' status, offer to roleplay interview questions.
    - If they have an 'Offer', congratulate them and offer negotiation advice.
    - Keep responses concise, encouraging, and actionable.
    `;

    // Convert history to API format
    const contents = history.map(msg => ({
      role: msg.role,
      parts: [{ text: msg.text }]
    }));

    // Add current user message
    contents.push({
      role: 'user',
      parts: [{ text: userMessage }]
    });

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: contents,
      config: {
        systemInstruction: systemInstruction,
      }
    });

    return response.text || "I didn't catch that. Could you say it again?";
  } catch (error) {
    console.error("Chatur Error:", error);
    return "I'm feeling a bit overwhelmed. Let's try again in a moment.";
  }
};
